format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$status\
$container\
$shell\
$fill\
$cmd_duration $jobs $time $battery$memory_usage\
$line_break\
$character"""

[time]
disabled = false
style = "bold green"
format = "[$time]($style)"

[fill]
symbol = ' '
style = ''

[battery]
full_symbol = '🔋'
charging_symbol = '⚡️'
discharging_symbol = '💀'

[[battery.display]]
threshold = 100
style = 'bold red'

[memory_usage]
disabled = false
threshold = -1
symbol = ''
style = 'bold dimmed green'

[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Macos = "🐈"
